#' Generate an array of possible outcome scenarios
#'
#' This functions generates an array of possible outcome scenarios. Each row
#' of the array is a scenario vector. The array starts with `k` inactive
#' baskets and 0 active baskets and then increments in steps of `by` up to
#' `k` active baskets (or the next smaller multiple of `by`).
#'
#' @inheritParams baskwrap::setup_fujikawa_x
#'
#' @param p1 A numeric, the true response probability for the active baskets
#' @param by A numeric, increment of the scenario sequence, default: 1.
#'
#' @return A numeric array.
#' @export
#'
#' @examples
#' p1s <- get_p1s(k = 3, p0 = 0.2, p1 = 0.5)
get_p1s <- function(k, p0, p1, by = 1){
  steps <- c(0, seq(from = by, to = k, by = by))
  return(t(sapply(steps,
                function(times){
                  return(t(c(rep(p0, k - times),
                           rep(p1, times))))
                })))
}

#' Generate a scenario of possible outcomes
#'
#' A wrapper of `get_p1s()` that also returns the input values `k` and
#' `p0` as part of a list.
#'
#' @inheritParams get_p1s
#'
#' @return A list with components `k`, `p0` and `p1s`,
#' where `p1s` is generated by the the function `get_p1s`.
#' @export
#'
#' @examples
#' scenario <- get_scenarios(k = 3, p0 = 0.2, p1 = 0.5)
get_scenarios <- function(k, p0, p1, by = 1){
  return(list(k = k,
              p0 = p0,
              p1s = get_p1s(k, p0, p1, by)))
}
